/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments */
/* Felucca menu (HOME held): a list that scrolls (MENU_VIS rows shown, the selected one kept in the middle: no state),
 * its rows in menu_items.c (the settings, shared with the editor's MENU_DESC / MENU_SET). No BACK row: OCT- is back.
 * The two-valued rows are bits of ui_prefs (MENU_FLAGS). PRESETS scrolls from ABOUT through all credits.
 * ui.menu: 1 list, 2 information. */
/* ------------------------------------------------------------ menu --- */
/* (the rows, their values and names, usb_serial_apply: menu_items.c) */

/* https://hugelton.github.io/Felucca, QR version 3, correction M, generated by CoreImage.
 * One row per word, leftmost module in bit 0; the constant matrix needs no encoder or RAM. */
static const uint32_t ABOUT_QR[29] = {
    0x1FCD247Fu, 0x1059C541u, 0x1745765Du, 0x1758E85Du, 0x174E575Du, 0x104C3A41u,
    0x1FD5557Fu, 0x000B7000u, 0x091BCA55u, 0x1270DC8Au, 0x1DB4375Au, 0x083E9FA1u,
    0x1A63124Eu, 0x12513981u, 0x1AE2524Du, 0x0A2E78A0u, 0x1A7F4FC3u, 0x167154B0u,
    0x19A228D5u, 0x0A561C2Au, 0x01F10B4Du, 0x1D1B3F00u, 0x1B5A467Fu, 0x1B13F641u,
    0x11F24D5Du, 0x1D1B625Du, 0x1389315Du, 0x08DFD641u, 0x1813977Fu,
};

static void draw_about_qr(int32_t x, int32_t y)
{
    uint32_t row, col;
    cv_rect(x, y, 74, 74, UI_QR_LIGHT);             /* fixed light / dark, independent of the palette */
    for (row = 0; row < 29u; row++)
        for (col = 0; col < 29u; col++)
            if ((ABOUT_QR[row] >> col) & 1u)
                cv_rect(x + 8 + (int32_t)col * 2, y + 8 + (int32_t)row * 2, 2, 2, UI_QR_DARK);
}

/* All notices are in flash. Wrap at the font's actual width, without dropping URL
 * characters; the same layout computes the scroll limit and draws clipped bands.
 * Mixed case here (long text); S throughout, the title in L. */
#define MENU_DOC_H 196                                /* the document: screen rows 24..220 */
enum { MC_TEXT, MC_TITLE, MC_URL };
typedef struct { const char *text; uint8_t kind; } menu_credit_t;
static const menu_credit_t MENU_CREDITS[] = {
    {"H\xFCgelton Instruments / OWN WORK", MC_TITLE},  /* Felucca's own: above; these are ours too */
    {"Leo Kuroshita", MC_TEXT},
    {"CrispyZebra (PHASE waveforms), the DRUM voices, the Sample Pack: GPL-3.0", MC_TEXT},
    {"Fukiai icon font: MIT", MC_TEXT},
    {"https://github.com/hugelton", MC_URL},
    {"", MC_TEXT},
    {"KLATTSCH / VOICE REFERENCE", MC_TITLE},
    {"Tony Gies / MIT", MC_TEXT},
    {"https://github.com/tgies/klattsch", MC_URL},
    {"", MC_TEXT},
    {"DAISYSP / PHYS PORT", MC_TITLE},
    {"Electrosmith, Emilie Gillet", MC_TEXT},
    {"MIT", MC_TEXT},
    {"https://github.com/electro-smith/DaisySP", MC_URL},
    {"", MC_TEXT},
    {"DEXED + MSFA / FM6 PORT", MC_TITLE},
    {"Pascal Gauthier, Google Inc.", MC_TEXT},
    {"msfa: Apache-2.0, Dexed: GPL-3.0", MC_TEXT},
    {"https://github.com/asb2m10/dexed", MC_URL},
    {"", MC_TEXT},
    {"RINGS / PHYS PORT", MC_TITLE},
    {"Emilie Gillet / MIT", MC_TEXT},
    {"https://github.com/pichenettes/eurorack", MC_URL},
    {"", MC_TEXT},
    {"INTER TIGHT / FONT", MC_TITLE},
    {"The Inter Project Authors", MC_TEXT},
    {"SIL Open Font License 1.1", MC_TEXT},
    {"https://github.com/rsms/inter-tight", MC_URL},
    {"", MC_TEXT},
    {"VSCO-2 CE + VCSL / SAMPLES", MC_TITLE},
    {"Versilian Studios / CC0 1.0", MC_TEXT},
    {"https://github.com/sgossner/VSCO-2-CE", MC_URL},
    {"https://github.com/sgossner/VCSL", MC_URL},
    {"", MC_TEXT},
    {"VOICE / RESEARCH", MC_TITLE},
    {"Dennis H. Klatt (1980)", MC_TEXT},
    {"https://doi.org/10.1121/1.383940", MC_URL},
    {"Hillenbrand, Getty, Clark and Wheeler (1995)", MC_TEXT},
    {"https://doi.org/10.1121/1.411872", MC_URL},
};

static int32_t menu_text(const char *s, int32_t y, uint16_t col, int draw)
{
    while (*s) {
        char line[64];
        uint32_t n = 0, space = 0, take, prev = 0;
        int32_t pen = 0;                                 /* 1/16 px, as text_w adds it up */
        while (s[n] && n < sizeof line - 1u) {
            uint32_t c = (uint8_t)s[n];
            line[n] = s[n];
            line[n + 1u] = 0;
            pen += (prev ? kern(&AF_S, prev, c) : 0) + AF_S.g[glyph(&AF_S, c)].adv;
            prev = c;
            if ((pen + 8) >> 4 > 226)
                break;
            if (s[n] == ' ')
                space = n;
            n++;
        }
        take = s[n] && space ? space : n;
        if (!take) take = 1;                         /* progress even for an unusually wide glyph */
        line[take] = 0;
        if (draw && y + AF_S.h > 0 && y < MENU_DOC_H)
            cv_text(6, y, &AF_S, line, col);
        y += 18;
        s += take;
        while (*s == ' ') s++;
    }
    return y;
}

static int32_t menu_document(int32_t y, int draw)
{
    uint32_t i;
    if (draw) {
        cv_text(6, y + 2, &AF_L, "FELUCCA", T_THEME);
        cv_text(6, y + 38, &AF_S, "Multi-engine synthesizer", T_TEXT);
        cv_text(6, y + 58, &AF_M, FELUCCA_VERSION, T_THEME);
        cv_text_r(232, y + 61, &AF_S, __DATE__, T_MID, T_BG);
        cv_text(6, y + 82, &AF_S, "(C) 2026 Leo Kuroshita", T_TEXT);
        cv_text(6, y + 100, &AF_S, "H\xFCgelton Instruments", T_TEXT);
        cv_text(6, y + 118, &AF_S, "GPL-3.0-only", T_TEXT);
        cv_text(6, y + 138, &AF_S, "hugelton.github.io", T_MID);
        cv_text(6, y + 156, &AF_S, "/Felucca", T_MID);
        cv_text(6, y + 180, &AF_S, "hugelton.com", T_MID);
        draw_about_qr(158, y + 122);
    }
    y = menu_text("CREDITS", y + 216, T_THEME, draw) + 8;
    for (i = 0; i < NELEM(MENU_CREDITS); i++) {
        const menu_credit_t *c = &MENU_CREDITS[i];
        const char *text = c->text;
        /* Display host/path once; the full source URL stays in the flash table. */
        if (c->kind == MC_URL && str_len(text) >= 8u && !memcmp(text, "https://", 8))
            text += 8;
        if (!text[0]) y += 8;
        else y = menu_text(text, y, c->kind == MC_TITLE ? T_THEME : c->kind == MC_URL ? T_MID : T_TEXT, draw);
    }
    y = menu_text("LICENSES + SOURCE", y + 12, T_THEME, draw);
    y = menu_text("DRUM + own samples: GPL-3.0-only", y, T_TEXT, draw);
    y = menu_text("Fonts and icons: their licences travel with the source and the release files.", y, T_TEXT, draw);
    y = menu_text("NO WARRANTY", y, T_TEXT, draw);
    y = menu_text("Full notices in source:", y + 8, T_TEXT, draw);
    y = menu_text("github.com/hugelton/Felucca", y, T_MID, draw);
    return y + 4;
}
static int32_t menu_scroll_max(void)
{
    int32_t h = menu_document(0, 0);
    return h > MENU_DOC_H ? h - MENU_DOC_H : 0;
}

/* the menu's header (0..24): its icon and title, the REC mark, the way back */
static void menu_head(void)
{
    cv_begin(240, H_HEAD, T_BG);
    GFX_HOOK_ALIGN(0, HEAD_MY + AF_M_CAP_Y, 0, HEAD_MY + AF_M_CAP_Y + AF_M_CAP_H, AL_V, "header icon on its title's line");
    cv_icon_mid(8, H_HEAD / 2, 16, ui.menu == 2 ? ICON_X_INFO : ICON_X_COG, T_THEME, T_BG);   /* (as draw_head's) */
    GFX_HOOK_ALIGN(0, 0, 0, H_HEAD, AL_V, "header text on its middle");
    cv_text(30, HEAD_MY, &AF_M, ui.menu == 2 ? "ABOUT / CREDITS" : "MENU", T_TEXT);
    if (ui.menu >= 2) {                               /* the way back at the right, the REC mark before it (then */
        const char *w = song.rec ? 0 : "BACK";        /* the keycap goes without its word: no room for both) */
        int32_t x = 232 - kh_w(KC_OCTDN, w);
        GFX_HOOK_ALIGN(0, 0, 0, H_HEAD, AL_V, "header text on its middle");
        cv_key_hint(x, HALF_UP(H_HEAD - KC_H), KC_OCTDN, w, 1, T_BG);
        draw_rec_mark(x - 20, T_BG);
    } else {
        draw_rec_mark(178, T_BG);
    }
    cv_blit(0, Y_HEAD);
}

/* the list: 24 px SURF rows 25 px apart from y 30, the selected one THEME with INK;
 * a 16 px icon, the name (S), the value (M) at the right; COLOR shows the palette's five colours.
 * MENU_VIS rows shown from menu_top(), a scroll bar at the right when there are more.
 * Drawn in two bands (the canvas holds 124 rows), split at y 130 between two rows */
#define MENU_Y0 30
#define MENU_ROW 25
#define MENU_SPLIT 130
#define MENU_VIS 7u
#define MENU_R (MI_COUNT > MENU_VIS ? 226 : 232)       /* a row's width (room for the scroll bar) */
static uint32_t menu_top(void)                         /* the first row shown: the selected one in the middle */
{
    uint32_t s = ui.menu_sel;
    if (MI_COUNT <= MENU_VIS || s < MENU_VIS / 2u)
        return 0;
    return s - MENU_VIS / 2u > MI_COUNT - MENU_VIS ? MI_COUNT - MENU_VIS : s - MENU_VIS / 2u;
}
static const khint_t MENU_KEYS[3] = {{KC_PRESETS, "MOVE"}, {KC_OCTUP, "OK"}, {KC_OCTDN, "BACK"}};
static void draw_menu(void)
{
    static const uint16_t ICO[MI_COUNT] = {ICON_X_PALETTE, ICON_SHAPE, ICON_SIZE, ICON_RATE, ICON_X_STAR_O, ICON_X_TIMER, ICON_X_KNOB,
                                           ICON_X_FX, ICON_TEMPO, ICON_X_SPEAKER, ICON_X_USB, ICON_X_DOC, ICON_X_DOCTOR, ICON_X_INFO};
    uint32_t i, pass, top = menu_top(), sig = ui.menu * 7u + ui.menu_sel * 131u + settings.palette * 1009u +
                            settings.lowcut * 7919u + settings_hold * 3511u + settings_leds * 6151u + ui_prefs * 4099u + ui_style * 257u +
                            song.rec * 65537u + song.sel * 13u +
                            (ui.menu == 2 ? ui.menu_scroll * 48611u : 0u);
    if (!ui.force && sig == ui.menu_sig)
        return;
    ui.menu_sig = sig;
    menu_head();
    if (ui.menu >= 2) {
        int32_t scroll = ui.menu_scroll, max = menu_scroll_max();
        int32_t thumb = MENU_DOC_H * MENU_DOC_H / (max + MENU_DOC_H);
        if (thumb < 12) thumb = 12;
        for (pass = 0; pass < 2u; pass++) {
            cv_begin(240, pass ? MENU_DOC_H - 124u : 124u, T_BG);
            cv_oy = pass ? -124 : 0;
            cv_scroll = 1;
            menu_document(-scroll, 1);
            cv_scroll = 0;
            cv_rrect(235, 2, 3, MENU_DOC_H - 4, 1, T_LINE, T_BG);           /* the scroll bar */
            cv_rrect(235, 2 + (max ? scroll * (MENU_DOC_H - 4 - thumb) / max : 0), 3, thumb, 1, T_MID, T_LINE);
            cv_oy = 0;
            cv_blit(0, H_HEAD + pass * 124u);
        }
        cv_begin(240, 240 - (H_HEAD + MENU_DOC_H), T_BG);
        cv_key_hint(8, 4, KC_PRESETS, "SCROLL", 1, T_BG);
        cv_blit(0, H_HEAD + MENU_DOC_H);
        return;
    }
    for (pass = 0; pass < 2u; pass++) {
        int32_t top_y = pass ? MENU_SPLIT : H_HEAD;
        cv_begin(240, (uint32_t)(pass ? 240 - MENU_SPLIT : MENU_SPLIT - H_HEAD), T_BG);
        cv_oy = -top_y;                               /* drawn in screen rows */
        if (ux.style && !pass)                        /* LINE: a rule under the header, one under each row */
            cv_rule(4, (H_HEAD + MENU_Y0 - 2) / 2, MENU_R, 1);
        for (i = top; i < top + MENU_VIS && i < MI_COUNT; i++) {
            int32_t y = MENU_Y0 + (int32_t)(i - top) * MENU_ROW, vr = MENU_R - 4;   /* vr: the values' right edge */
            int32_t ny = y + CAP_IN(S, 24), vy = y + CAP_IN(M, 24);           /* the name, the value: centred */
            int sel = i == ui.menu_sel;
            uint16_t bg = sel ? T_THEME : T_SURF, fg = sel ? T_INK : T_TEXT, val = sel ? T_INK : T_THEME;
            if (y + 24 <= top_y || y >= top_y + (int32_t)cv_h)
                continue;
            cv_rrect(4, y, MENU_R, 24, 6, bg, T_BG);
            if (ux.style)
                cv_rule(4, y + 24, MENU_R, 1);
            GFX_HOOK_ALIGN(0, y, 0, y + 24, AL_V, "menu row icon centred up/down");
            cv_icon_in(12, y, 0, 24, 16, ICO[i], sel ? T_INK : T_MID, bg);
            GFX_HOOK_ALIGN(0, y, 0, y + 24, AL_V, "menu row name centred up/down");
            cv_text_on(36, ny, &AF_S, MI_NAME[i], fg, bg);
            if (i < MI_VALUES)
                GFX_HOOK_ALIGN(0, y, 0, y + 24, AL_V, "menu row value centred up/down");
            if (i < MI_VALUES && i != MI_HOLD && i != MI_COLOR)
                cv_text_r(vr, vy, &AF_M, menu_vname(i, menu_get(i)), val, bg);
            if (i == MI_HOLD) {                         /* "0.4" and its unit */
                char b[8] = "0.4";
                b[2] = (char)('0' + HOLD_MS[settings_hold % 4u] / 100u);
                GFX_HOOK_ALIGN(0, 0, 0, vy + AF_M.asc, AL_B, "menu row unit on its value's baseline");
                cv_text_r(cv_text_r(vr, vy + AF_M.asc - AF_S.asc, &AF_S, "s", val == T_INK ? T_INK : T_MID, bg) - 3, vy, &AF_M, b,
                          val, bg);
            }
            if (i == MI_COLOR) {
                uint32_t k;
                const uint16_t *tok = &T_BG;            /* BG SURF TEXT THEME ACCENT */
                int32_t x0 = vr - 76;
                cv_text_r(x0 - 6, vy, &AF_M, UI_PALETTES[settings.palette % NPALETTES].name, val, bg);
                for (k = 0; k < 5u; k++) {
                    cv_rrect(x0 + (int32_t)k * 15, y + 6, 12, 12, 3, T_RAISE, bg);     /* a rim for the dark ones */
                    cv_rrect(x0 + 1 + (int32_t)k * 15, y + 7, 10, 10, 2, tok[k], T_RAISE);
                }
            }
        }
        if (MI_COUNT > MENU_VIS) {                      /* the scroll bar: the rows shown, of all */
            int32_t h = (int32_t)(MENU_VIS * MENU_ROW) - 1, th = h * (int32_t)MENU_VIS / (int32_t)MI_COUNT;
            cv_rrect(234, MENU_Y0, 3, h, 1, T_LINE, T_BG);
            cv_rrect(234, MENU_Y0 + (h - th) * (int32_t)top / (int32_t)(MI_COUNT - MENU_VIS), 3, th, 1, T_MID, T_LINE);
        }
        cv_key_row(8, 232, 207, MENU_KEYS, 3, 7u, T_BG);
        cv_oy = 0;
        cv_blit(0, (uint32_t)top_y);
    }
}
static void enc_drop(void)                             /* knob turns nobody takes */
{
    uint32_t k;
    for (k = 0; k < NE; k++)
        panel_enc(k);
}

static void menu_close(void)
{
    settings_save();                                   /* palette / panel table, if changed */
    ui.menu = 0;
    ui.force = 1;
    go_home();
}

/* menu: PRESETS moves, OCT+ confirms, OCT- cancels (ABOUT -> list -> close) */
static void menu_input(uint32_t oct)                  /* oct: ui_input.c oct_taps */
{
    int32_t s;
    uint32_t ok = (oct >> 1) & 1u, back = oct & 1u;
    if (back) {
        if (ui.menu >= 2)
            ui.menu = 1, ui.force = 1;
        else
            menu_close();
        return;
    }
    if ((s = panel_enc(EN_PRESET)) != 0 && ui.menu == 1)
        ui.menu_sel = (uint8_t)((ui.menu_sel + (s > 0 ? 1u : MI_COUNT - 1u)) % MI_COUNT);
    else if (s != 0 && ui.menu >= 2) {             /* bounded document scrolling */
        ui.menu_scroll = (uint16_t)clamp((int32_t)ui.menu_scroll + clamp(s, -128, 128) * 18, 0, menu_scroll_max());
    }
    s = panel_enc(EN_K1);
    if ((s != 0 || ok) && ui.menu == 1 && ui.menu_sel < MI_VALUES) {
        /* KNOB 1 steps (the two-valued rows: right = the second value (ON), left = the first), OCT+ steps and wraps;
         * COLOR previews the palette, STYLE is drawn so from the next frame (FX LATCH: the latched effects are off
         * while the menu is up) */
        menu_put(ui.menu_sel, menu_step(ui.menu_sel, s));
        ok = 0;
    }
    if (ok && ui.menu == 1) {
        switch (ui.menu_sel) {
        case MI_PANEL:
            panel_setup();
            ui.force = 1;
            break;
        case MI_ABOUT:
            ui.menu = 2;
            ui.menu_scroll = 0;
            ui.force = 1;
            break;
        default:
            menu_close();
            break;
        }
    }
    enc_drop();                                        /* swallow the rest while the menu is up */
}
